//! Actix-web框架的路由注册器

use actix_web::{web, App, HttpServer, HttpResponse, Result as ActixResult};

/// 启动Actix-web服务器的便捷函数，自动配置所有使用uni_routing宏定义的路由
pub async fn start_server() -> std::io::Result<()> {
    // 注意：env_logger 应该由应用程序初始化
    
    println!("🚀 Starting Actix-web server with uni_routing...");
    println!("🌐 Server starting on http://localhost:8080");
    println!("📖 Swagger UI: http://localhost:8080/swagger");
    println!("📄 OpenAPI Spec: http://localhost:8080/swagger/openapi.json");
    println!();
    
    HttpServer::new(|| {
        App::new()
            // 健康检查端点
            .service(
                web::resource("/api/health")
                    .route(web::get().to(health_check))
            )
            // 用户管理端点
            .service(
                web::resource("/api/users")
                    .route(web::get().to(get_users))
                    .route(web::post().to(create_user))
            )
            // 单个用户操作端点
            .service(
                web::resource("/api/users/{id}")
                    .route(web::get().to(get_user_by_id))
                    .route(web::put().to(update_user))
                    .route(web::delete().to(delete_user))
            )
            // Swagger文档端点
            .service(
                web::resource("/swagger")
                    .route(web::get().to(swagger_ui))
            )
            .service(
                web::resource("/swagger/openapi.json")
                    .route(web::get().to(openapi_spec))
            )
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}

/// Swagger UI页面
async fn swagger_ui() -> ActixResult<HttpResponse> {
    let html = r#"
<!DOCTYPE html>
<html>
<head>
    <title>Uni Routing API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@4/swagger-ui.css" />
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; background: #fafafa; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@4/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@4/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            const ui = SwaggerUIBundle({
                url: '/swagger/openapi.json',
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>
    "#;
    
    Ok(HttpResponse::Ok()
        .content_type("text/html")
        .body(html))
}

/// OpenAPI规范端点
async fn openapi_spec() -> ActixResult<HttpResponse> {
    let spec = generate_openapi_docs();
    Ok(HttpResponse::Ok().json(spec))
}

// 这些函数将由示例项目中的实际函数替换
// 这里只是占位符，实际使用时会链接到示例中的函数

#[allow(dead_code)]
async fn health_check() -> ActixResult<HttpResponse> {
    Ok(HttpResponse::Ok().json(serde_json::json!({
        "message": "Health check - implement in example"
    })))
}

#[allow(dead_code)]
async fn get_users() -> ActixResult<HttpResponse> {
    Ok(HttpResponse::Ok().json(serde_json::json!({
        "message": "Get users - implement in example"
    })))
}

#[allow(dead_code)]
async fn create_user() -> ActixResult<HttpResponse> {
    Ok(HttpResponse::Created().json(serde_json::json!({
        "message": "Create user - implement in example"
    })))
}

#[allow(dead_code)]
async fn get_user_by_id() -> ActixResult<HttpResponse> {
    Ok(HttpResponse::Ok().json(serde_json::json!({
        "message": "Get user by ID - implement in example"
    })))
}

#[allow(dead_code)]
async fn update_user() -> ActixResult<HttpResponse> {
    Ok(HttpResponse::Ok().json(serde_json::json!({
        "message": "Update user - implement in example"
    })))
}

#[allow(dead_code)]
async fn delete_user() -> ActixResult<HttpResponse> {
    Ok(HttpResponse::Ok().json(serde_json::json!({
        "message": "Delete user - implement in example"
    })))
}

#[allow(dead_code)]
fn generate_openapi_docs() -> serde_json::Value {
    serde_json::json!({
        "openapi": "3.0.0",
        "info": {
            "title": "Uni Routing API",
            "version": "1.0.0",
            "description": "API documentation generated by uni_routing"
        },
        "paths": {}
    })
}